name = "PhyloPOMP"
uuid = "d3093253-1426-44ff-8fa8-1ab5fe440962"
version = "0.0.1"
authors = ["Aaron A. King <kingaa@umich.edu>"]

[deps]
PartiallyObservedMarkovProcesses = "32433216-4d85-4b2d-94ed-a614743ba12b"

[compat]
PartiallyObservedMarkovProcesses = "0.5"
julia = "1.11"
